import { Session } from "next-auth";
import { headers } from "next/headers";
import { Header } from "@/components/Header";
import "./globals.css";
import AuthContext from "./AuthContext";

export const metadata = {
  title: "Colabora",
  description: "Project generated by some homework of web development",
};

async function getSession(cookie: string): Promise<Session> {
  const response = JSON.parse('{"name":"", "age":30, "city":"New York"}');

  const session = response.name;

  return Object.keys(session).length > 0 ? session : null;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession(headers().get("cookie") ?? "");
  return (
    <html lang="pt-BR">
      <body>
        <AuthContext session={session}>
          <Header />
          {children}
        </AuthContext>
      </body>
    </html>
  );
}
