import { Header } from "@/components/Header";
import "./globals.css";
import { Open_Sans } from "next/font/google";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Home | cola.bora",
  description: "Project generated by some homework of web development",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={openSans.className}>
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
